name: tictacverse
version: 1.0.2+6
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_mobile_ads: ^5.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/symbols/board/
    - assets/symbols/x/
    - assets/symbols/o/
    - assets/audio/sfx/
    - assets/audio/music/
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0B1020"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  android: true
  ios: false

  color: "#0A3344"
  image: assets/icon/app_icon.png

  android_12:
    color: "#0A3344"
    image: assets/icon/app_icon.png
